#!/usr/bin/env ruby

# Okay.  So we get two args from svn.
#
# [1] - repo path
# [2] - revision number
#
# We then use this information to gather relevant data about the commit
# and do with it as we please.

path = ARGV[0]
rev = ARGV[1]

if (path.nil? || rev.nil?)
  puts "Usage: post-commit <repo path> <rev number>"
  exit
end

info = `svnlook info --revision #{rev} #{path}`

info_array = info.strip.split(/\n/, 4)

puts "Committer: #{info_array[0]}"
puts "When: #{info_array[1]}"
puts "Log: #{info_array[3]}"
