#!/usr/bin/env ruby

require 'drb'

# Okay.  So we get two args from svn.
#
# [1] - repo path
# [2] - revision number
#
# We then use this information to gather relevant data about the commit
# and do with it as we please.

path = File.expand_path(ARGV[0])
rev = ARGV[1]

if (path.nil? || rev.nil?)
  puts "Usage: post-commit <repo path> <rev number>"
  exit
end

DRb.start_service
sw = DRbObject.new(nil, 'druby://127.0.0.1:7666')

# The array contains this data:
# [0]: committer
# [1]: timestamp of commit
# [2]: Size of log entry, in bytes
# [3]: Log message
info_array = `svnlook info --revision #{rev} #{path}`.strip.split(/\n/, 4)

# dumb idea, it would wrap too many lines if multiple files...
#changed = `svnlook changed -r #{rev} #{path}`.strip

# guess what the repository name is
repos = path.split(/\//).last

# colorize it. we can make this look pretty later
message = "\0032#{info_array[0]}\003 * \0039#{repos}:/\003 \002[#{rev}]\002 - #{info_array[3]}"

sw.send_msg message
